import type { Metadata } from "next";
import "./globals.css";
import '../styles/index.scss';
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { MainLayout } from "@/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <AntdRegistry>
        <MainLayout>{children}</MainLayout>
      </AntdRegistry>
      </body>
    </html>
  );
}
